platform :ios, '{{{iosDeploymentTarget}}}'
require_relative '{{{nodeModulesRelativePath}}}/@react-native-community/cli-platform-ios/native_modules'

{{#extraPodspecsSources}}
{{{.}}}
{{/extraPodspecsSources}}

{{#extraPodfileStatements}}
{{{.}}}
{{/extraPodfileStatements}}

post_install do |installer|
  react_native_post_install(installer)

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end

    if (target.name&.eql?('FBReactNativeSpec'))
      target.build_phases.each do |build_phase|
        if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
          target.build_phases.move(build_phase, 0)
        end
      end
    end
  end
end

target '{{{projectName}}}' do
  # Pods for {{{projectName}}}
  pod 'FBLazyVector', :path => "{{{nodeModulesRelativePath}}}/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "{{{nodeModulesRelativePath}}}/react-native/React/FBReactNativeSpec"
  pod 'RCTRequired', :path => "{{{nodeModulesRelativePath}}}/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "{{{nodeModulesRelativePath}}}/react-native/Libraries/TypeSafety"
  pod 'React', :path => '{{{nodeModulesRelativePath}}}/react-native/'
  pod 'React-Core', :path => '{{{nodeModulesRelativePath}}}/react-native/'
  pod 'React-CoreModules', :path => '{{{nodeModulesRelativePath}}}/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '{{{nodeModulesRelativePath}}}/react-native/'
  pod 'React-RCTActionSheet', :path => '{{{nodeModulesRelativePath}}}/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '{{{nodeModulesRelativePath}}}/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '{{{nodeModulesRelativePath}}}/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '{{{nodeModulesRelativePath}}}/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '{{{nodeModulesRelativePath}}}/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '{{{nodeModulesRelativePath}}}/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '{{{nodeModulesRelativePath}}}/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '{{{nodeModulesRelativePath}}}/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '{{{nodeModulesRelativePath}}}/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '{{{nodeModulesRelativePath}}}/react-native/'

  pod 'React-cxxreact', :path => '{{{nodeModulesRelativePath}}}/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '{{{nodeModulesRelativePath}}}/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '{{{nodeModulesRelativePath}}}/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '{{{nodeModulesRelativePath}}}/react-native/ReactCommon/jsinspector'
  pod 'React-callinvoker', :path => "{{{nodeModulesRelativePath}}}/react-native/ReactCommon/callinvoker"
  pod 'React-runtimeexecutor', :path => "{{{nodeModulesRelativePath}}}/react-native/ReactCommon/runtimeexecutor"
  pod 'React-perflogger', :path => "{{{nodeModulesRelativePath}}}/react-native/ReactCommon/reactperflogger"
  pod 'ReactCommon/turbomodule/core', :path => "{{{nodeModulesRelativePath}}}/react-native/ReactCommon"
  pod 'Yoga', :path => '{{{nodeModulesRelativePath}}}/react-native/ReactCommon/yoga', :modular_headers => true

  pod 'DoubleConversion', :podspec => '{{{nodeModulesRelativePath}}}/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '{{{nodeModulesRelativePath}}}/react-native/third-party-podspecs/glog.podspec'
  pod 'RCT-Folly', :podspec => '{{{nodeModulesRelativePath}}}/react-native/third-party-podspecs/RCT-Folly.podspec'

{{#extraPods}}
  {{{.}}}
{{/extraPods}}

  use_native_modules!
end
