require_relative '{{{nodeModulesRelativePath}}}/react-native/scripts/react_native_pods'
require_relative '{{{nodeModulesRelativePath}}}/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '{{{iosDeploymentTarget}}}'

{{#extraPodspecsSources}}
{{{.}}}
{{/extraPodspecsSources}}

{{#extraPodfileStatements}}
{{{.}}}
{{/extraPodfileStatements}}

target '{{{projectName}}}' do
  config = use_native_modules!

  use_react_native!(
    :path => "{{{nodeModulesRelativePath}}}/react-native"
  )

{{#extraPods}}
  {{{.}}}
{{/extraPods}}

  post_install do |installer|
    react_native_post_install(installer)
  end
end
